### ISSUE TITLE
0-fee upgrade op

### ISSUE THREAD

**Issue by alcueca** [usmfum/USM#25]
0-fee upgrade op, to save users money if/when we need to push a fresh contract

**Comment by albertocuestacanada** [comment]
@jacob-eliosoff, I've been thinking on this.

Since we use the `Delegable` pattern, it would be trivial to code a contract that moves funds from USM1 to USM2 once the users give consent. My concern is how that would impact prices.

How would you move funds from one to the other? Would you just allow to move `USM` and `FUM` from v1 to v2 as long as the debt ratios in both are above maximum? Would you implement any restrictions?

**Comment by jacob-eliosoff** [comment]
Good question.
1. Migrating USM is easy b/c both v1 and v2 USM are (well, should be!) worth exactly $1.  So if the current ETH price was $300, and the user wanted to migrate 600 USM, we'd just move over the 600 USM + 2 ETH, no problem.  (And no fees.)  This would change the debt ratios of the two pools a bit, but that's OK.\
\
(There is a nuance there in that v1 and v2 might use different oracles with (slightly?) different ETH/USD prices.  But unless the v1 oracle had completely crapped out (eg, our source exchange went bust), this shouldn't be a big deal.)

2. Migrating FUM is on the face of it messier because the v1 and v2 FUM prices could be completely different - like, v1 could be $0.50 while v2 is $200!  But this is actually fine: we'd just match the ETH amount moved.  So assuming ETH = $300, v1 FUM = $0.50, and v2 FUM = $200, a user with $3,000 worth of v1 (6,000 v1 FUM) gets $3,000 worth of v2 (15 v2 FUM), plus the backing 10 ETH, moved over from the v1 pool.

My assumption in all of this is that migrations would be 0-fee, including no adjustments and no sliding prices.  That might open up some exploits, but only one-offs during migration - I'm not too worried about it.

I'd also suggest allowing them irrespective of debt ratios: the worst I can see happening there is someone migrates their v1 FUM while the debt ratio is > 100%, so the FUM they're migrating is worthless, so they get 0 v2 FUM.  Not ideal for them but no harm to the system.

We're helped in all this by the recurring principle that, fees and adjustments aside, none of our four operations change the FUM (or of course USM) price at all!  Fundamentally, the only thing that _does_ move FUM price is changes in the ETH/USD price.

**Comment by albertocuestacanada** [comment]
> My assumption in all of this is that migrations would be 0-fee, including no adjustments and no sliding prices. That might open up some exploits, but only one-offs during migration - I'm not too worried about it.

That's actually a big issue.

The whole assumption about `Proxy` is that it doesn't need any system permissions, only user permissions. Therefore anything implemented using the `Proxy` can't do anything than an user couldn't do himself.

For a migration that avoids sliding prices we need a backdoor, and that opens quite a can of worms.

**Comment by alexroan** [comment]
How big should this backdoor be? Does it only need to be there for the locked ETH (WEth) or is there more it needs to allow?

**Comment by jacob-eliosoff** [comment]
Yes @albertocuestacanada, I had in mind from the start that this would be a separate base operation bypassing the fees of other operations, not just a "convenience" (`Proxy`) function that calls existing functions.  But it's debatable.  In brief the tradeoff is:
- If we make it a separate function, it increases our attack surface.
- If we don't, migrating users pay fees, possibly huge fees: esp if they have large positions (that slide the price a lot, or move the price adjustments a lot), or migrate at the same time as other users (so the adjustments add a lot to the price).

I suspect once we implement it (I could take a stab) we'll see that the risk of exploitation isn't so bad.  I don't have a really strong preference though, if we end up finding it too messy we can drop it - I'm sure users will tolerate _some_ extras fees in the name of minimalism!

**Comment by jacob-eliosoff** [comment]
The key property that should reassure us a bit is that the `migrate()` function can only send ETH from the `ethPool` to a single address (ie, of the v2 contract) that we alone have the privkey to set.  Plus migrate v1 USM/FUM the user passes in to v2.  It's not like we're giving them a function that lets them send pool ETH to some random address they pass in.

**Comment by albertocuestacanada** [comment]
I can take a stab at a PR, it might make the discussion easier.

Tbh, my biggest concern is managing the right to nominate a v2 contract.

**Comment by albertocuestacanada** [comment]
Branch `feat/migrate-v2` contains an implementation for migration and escape hatch, if we decide to use it.

**Comment by jacob-eliosoff** [comment]
> Tbh, my biggest concern is managing the right to nominate a v2 contract.

Is a 2-of-3 multisig easy?  If so let's do that.  If not just a simple privkey shared by 2 or 3 of us ought to do.

**Comment by jacob-eliosoff** [comment]
> Tbh, my biggest concern is managing the right to nominate a v2 contract.

Is a 2-of-3 multisig easy?  If so let's do that.  If not just a simple privkey shared by 2 or 3 of us ought to do.

(That is, privkey to the v1 contract, whose only power in practice should be the power to set its `v2` variable.  Though hmmm would that also let us spend v1's ETH?  Maybe instead v1's constructor does `admin = [new address]`, and then setting the v2 address = setting `v1.admin.v2 = v2_`, and our admin privkey is the key to `v1.admin`, not to `v1` itself?  Anyway I'm sure there's some standard multisig design)

**Comment by alexroan** [comment]
https://github.com/ConsenSys/MultiSigWallet

Do we want more participants os the multisig than just us 3? Perhaps some top donators from our gitcoin grant?

**Comment by alexroan** [comment]
Also, let's leave these options here following our Telegram discussion:

a) No migration function, no owner
b) Deploy V1 with `onlyOwner` migration/safety hatch, renounce ownership once proven
c) Deploy V1 with a safety hatch and ownership as above & keep it around just in case

With the assumption that the owner would be a multisig.

**Comment by jacob-eliosoff** [comment]
We've been discussing this again, so note one potential gotcha: if we let users migrate from v1 to v2 at v2's ETH price, that could in some circumstances save users from getting funds stuck in v1 because v1's price broke (eg, got stuck at a low/high value).  BUT, we do need to be a bit careful, because this "v1 op at v2 price" functionality could make the ability to set `USMv1.upgradeContract = USMv2.address` prone to abuse - even if migration is totally opt-in.  Here's how:
1. Attacker gets ahold of the admin key letting them set `v1.upgradeContract` (or fine, we're the attacker)
2. Attacker mints 1 USM on v1
3. Attacker creates a `FakeUSMv2` contract whose ETH price (`latestPrice()`) is fixed at 0.000000001
4. Attacker calls the fn migrating their (and only their!) 1 v1 USM to `FakeUSMv2` at the v2 price.  But at that bogus low v2 ETH price, their 1 v1 USM is worth all the ETH in the v1 pool...

This isn't a big deal: we probably just need to keep migration from v1 at v1's own price (ie, prevent v1 or migration from ever depending on v2's price).  So yeah if the v1 price gets permanently borked the migration feature may not be able to save v1 users, that's OK.
