### ISSUE TITLE
Implement a basic UI

### ISSUE THREAD

**Issue by alexroan** [usmfum/USM#30]
Create a basic UI so users can interact with testnet USM using their preferred web3 provider.

**Comment by KennethAshley** [comment]
This is really interesting. Looking for a dApp dev?

**Comment by alexroan** [comment]
Hey Kenneth, we'd really appreciate your help!

I've got PR #31  in progress at the moment which is using React, Redux & nes.css for an 8-bit feel. Still working on the look and feel but to be honest that's not my forte. Haven't connected up to web3 to the contracts just yet, trying to find the time.

If you wanna check it out: clone, `git checkout feature/ui`, `cd client`, `npm install`, `npm run start` should start the dev server.

Have a dig through the code and let me know what you think you can help with :)

**Comment by KennethAshley** [comment]
@alexroan Sweet. I'll fork the repo and see what I can come up with. I'm a designer and developer so this is right up my alley!

**Comment by jacob-eliosoff** [comment]
Welcome Kenneth!

Nope, we're still finishing things up.  I'd love to deploy in the next couple months but nobody's promising anything, we want it to be good.

The ethos of the project is (decentralized!) **minimalism,** so we definitely don't want to go overboard with anything - either in terms of ornateness, features, or even effort!  I personally really adore the look Alex has come up with, though I'm no design expert.

Of course there's more room for play with the UI than with the smart contract itself, since there can be multiple UIs, and they can be modified.

Looking forward to anything you have to contribute and I hope you enjoy playing around with it!

**Comment by KennethAshley** [comment]
Jacob! Hope all is well. 

I think I have gleaned the style your going for. One of which I appreciate. Yea let me design a few things for you guys and you can tell me what you think.

**Comment by alexroan** [comment]
@KennethAshley The contracts do function, so If you want to test on a testnet just let us know, we can deploy the contracts in their current state on Kovan in a couple of minutes at no cost.

There's still a bit of work to do around finer testing and audits, so the insides might change, but the contract ABIs shouldn't at this stage.
