### ISSUE TITLE
Is this project active? 

### ISSUE THREAD

**Issue by akhekade** [usmfum/USM#84]
Can USM be deployed on ETH compatible chains? Is the project team open to working on commercial collaboration?

**Comment by jacob-eliosoff** [comment]
Hi @akhekade!  Sure, I expect the idea can be deployed on other chains.  I think they'd have to be their own stablecoins though, rather than a single asset portable across chains (like USDT is).  I'd be happy to give pointers to devs attempting such deployments, though the Eth deployment is my main focus right now just for practical reasons.  It would also kind of make sense for other deployments to wait a bit first in case our Eth version goes kaboom.
